application: <app-id>
version: 1
runtime: python27
api_version: 1
threadsafe: no


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/mail/.+
  script: handle_catchall.py
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

inbound_services:
- warmup
- mail

automatic_scaling:
  max_idle_instances: 1
  min_idle_instances: 1
